# Example pgsync job for unidirectional async sync of the users table.
# Replace the DSN placeholders with concrete connection strings.
# https://github.com/timeplus-io/pgsync

jobs:
  users_one_way:
    source:
      dsn: postgresql://replica:password@global-db:5432/account?sslmode=disable
    destination:
      dsn: postgresql://replica:password@cn-db:5432/account?sslmode=disable
    schema: public
    tables:
      users:
        delete: false
        columns:
          - uuid
          - username
          - password
          - email
          - role
          - level
          - groups
          - permissions
          - created_at
          - updated_at
          - version
          - origin_node
          - mfa_totp_secret
          - mfa_enabled
          - mfa_secret_issued_at
          - mfa_confirmed_at
          - email_verified_at
          - email_verified
    batch_size: 5000
    snapshot: true
    poll_interval: 30s
