mode: "agent"

log:
  level: info

agent:
  id: "edge-node-1"
  controllerUrl: "https://accounts.svc.plus"
  apiToken: "replace-with-agent-token"
  httpTimeout: 15s
  statusInterval: 1m
  syncInterval: 5m
  tls:
    insecureSkipVerify: false

xray:
  sync:
    enabled: true
    interval: 5m
    templatePath: "account/config/xray.config.template.json"
    outputPath: "/usr/local/etc/xray/config.json"
    validateCommand: []
    restartCommand:
      - "systemctl"
      - "restart"
      - "xray.service"
