log:
  level: info

server:
  addr: ":8443"
  readTimeout: 15s
  writeTimeout: 15s
  tls:
    certFile: "/etc/ssl/svc.plus.pem"
    keyFile: "/etc/ssl/svc.plus.rsa.key"
    clientCAFile: ""
    redirectHttp: true

store:
  driver: "postgres"
  dsn: "postgres://shenlan:password@127.0.0.1:5432/account?sslmode=disable"
  maxOpenConns: 30
  maxIdleConns: 10

session:
  ttl: 24h
  cache: "redis"
  redis:
    addr: "127.0.0.1:6379"
    password: ""
