log:
  level: info
global:
  redis:
    addr: 127.0.0.1:6379
  vectordb:
    pgurl: postgres://user:password@127.0.0.1:5432/postgres
  datasources: []
  embedding:
    base_url: http://127.0.0.1:11434
    token: ""
    dimension: 1536
sync:
  repo:
    proxy: ""
api:
  askai:
    timeout: 100
    retries: 0
