env:
  CHUTES_API_TOKEN: "cpk_xxxxxxxxxxxxxxxxxxxxxxxx"
model:
  - 'moonshotai/Kimi-K2-Instruct'
askai:
  timeout: 100
  retries: 3
RAG:
  redis:
    addr: "127.0.0.1:6479"
    password: ""
  module: "moonshotai/Kimi-K2-Instruct"
  embedder: "openai"
  vectordb:
    pgurl: "postgres://myuser:mypassword@127.0.0.1:5432/mydb?sslmode=disable"
    pg_host: "127.0.0.1"
    pg_port: 5432
    pg_user: myuser
    pg_password: mypassword
    pg_db_name: mydb
    pg_sslmode: disable
  datasources:
    - name: Xstream
      repo: https://github.com/svc-design/Xstream
      path: docs
    - name: XControl
      repo: https://github.com/svc-design/XControl
      path: docs
    - name: documents
      repo: https://github.com/svc-design/documents
      path: /

