global:
  proxy: "" # optional proxy like socks5://127.0.0.1:1080
  redis:
    addr: "127.0.0.1:6379"
    password: ""
  vectordb:
    pgurl: "postgres://shenlan:password@127.0.0.1:5432/postgres"
  datasources:
    - name: Xstream
      repo: https://github.com/svc-design/Xstream
      path: docs
    - name: XControl
      repo: https://github.com/svc-design/XControl
      path: docs
    - name: documents
      repo: https://github.com/svc-design/documents
      path: /

provider:
  - name: allama
    base_url: http://localhost:11434
    models:
      - 'gpt-oss:20b'
  - name: chutes
    base_url: https://llm.chutes.ai/
    token: "cpk_9221badbda89490ea8f2fe8f3818eebc.5bd47a04456b5f9f94b88066fd18faa2.2jsXIytq11GcDmXpEGNd1ls2zeQWn4US"
    models:
      - 'moonshotai/Kimi-K2-Instruct'

embedding:
  provider: chutes
  model: "BAAI/bge-m3"
  dimension: 0
  rate_limit_tpm: 120000
  max_batch: 64
  max_chars: 8000

chunking:
  max_tokens: 800
  overlap_tokens: 80
  prefer_heading_split: true
  include_exts: [".md", ".mdx"]
  ignore_dirs: [".git", "node_modules", "dist", "build"]

api:
  askai:
    timeout: 100
    retries: 3
