name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Please describe what you'd like to see added or improved.

  - type: input
    id: summary
    attributes:
      label: Feature summary
      description: Briefly describe the feature.
      placeholder: "e.g. Add role-based access control to the dashboard"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem or need would this feature address?
      placeholder: "Currently all users have the same permissions. We need finer access control."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How do you imagine this working?
      placeholder: "Introduce roles (Admin, Operator, User) with configurable permissions via API."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "We could temporarily use manual config, but it's not scalable."

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any extra info, mockups, or references.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for similar requests
          required: true
        - label: This feature aligns with the project’s roadmap
