name: "📘 Development Roadmap Task"
description: "用于跟踪角色体系与管理面板开发进度的标准任务模板"
title: "[Task] "
labels: ["roadmap", "development", "tracking"]
assignees:
  - shenlan
body:
  - type: dropdown
    id: task_id
    attributes:
      label: 🧩 任务选择
      description: 请选择本 Issue 所对应的阶段任务
      options:
        - "Task 1 — Add role metadata to account models"
        - "Task 2 — Design permission matrix storage"
        - "Task 3 — Add user metrics aggregation logic"
        - "Task 4 — Expand User type & fetchSessionUser"
        - "Task 5 — Create homepage management panel layout"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 📋 概要描述 / Summary
      description: 简要说明此任务的目标与核心改动（中英文均可）
      placeholder: |
        e.g. 为后端账号体系增加角色/组/权限字段，并透传到前端 session，解锁管理功能。
    validations:
      required: true

  - type: dropdown
    id: dependencies
    attributes:
      label: 🔗 依赖任务 / Dependencies
      description: 选择本任务依赖的上游任务（如无则留空）
      multiple: true
      options:
        - "None"
        - "Task 1 — Add role metadata to account models"
        - "Task 2 — Design permission matrix storage"
        - "Task 3 — Add user metrics aggregation logic"
        - "Task 4 — Expand User type & fetchSessionUser"
        - "Task 5 — Create homepage management panel layout"

  - type: textarea
    id: deliverables
    attributes:
      label: 🎯 交付内容 / Deliverables
      description: 列出本任务完成后预期的可验证成果或文件路径
      placeholder: |
        - 更新 account/internal/store/store.go
        - 新增 server/api/admin_users_metrics.go
        - 修改 ui/homepage/app/panel/management/page.tsx

  - type: textarea
    id: acceptance
    attributes:
      label: ✅ 验收标准 / Acceptance Criteria
      description: 描述完成定义 (DoD)，包括代码合并、测试覆盖、API 可用性等。
      placeholder: |
        - 单元测试覆盖率 ≥ 80%
        - API /api/admin/users/metrics 正常返回
        - 前端展示角色徽章与权限矩阵正确

  - type: input
    id: milestone
    attributes:
      label: 🗓️ 里程碑 / Milestone
      description: 对应版本或阶段（例如 v0.5.0 或 “Phase 2”）
      placeholder: v0.5.0

  - type: dropdown
    id: labels
    attributes:
      label: 🏷️ 标签 / Labels
      description: 为任务打上关键分类标签
      multiple: true
      options:
        - backend
        - frontend
        - auth
        - metrics
        - schema
        - ui
        - docs
        - testing
        - high-priority

  - type: textarea
    id: notes
    attributes:
      label: 🧠 备注 / Notes
      description: 其他需要记录的上下文、技术决策或风险
      placeholder: |
        - Task 2 / Task 3 可并行开发
        - 需在 Task 1 完成后同步 User.role 字段到 session

