global:
  redis:
    addr: "127.0.0.1:6479"
    password: ""
  vectordb:
    pgurl: "postgres://user:password@127.0.0.1:5432"
  datasources:
    - name: Xstream
      repo: https://github.com/svc-design/Xstream
      path: docs
    - name: XControl
      repo: https://github.com/svc-design/XControl
      path: docs
    - name: documents
      repo: https://github.com/svc-design/documents
      path: /

provider:
  - name: chutes
    base_url: https://llm.chutes.ai/
    token: "cpk_xxxxxxx"
    models:
      - 'moonshotai/Kimi-K2-Instruct'

# embedding 段为空时自动复用 llm（见代码回退逻辑）
embedding:
  provider: chutes             # openai|azure|custom
  base_url: ""                  # 为空 -> 用 provider base_url: + "/v1"
  model: "text-embedding-3-large"
  api_key_env: ""              # 为空 -> 直接用 llm.token
  dimension: 0                 # 0 = 首次响应自动探测维度
  rate_limit_tpm: 120000
  max_batch: 64
  max_chars: 8000

chunking:
  max_tokens: 800
  overlap_tokens: 80
  prefer_heading_split: true
  include_exts: [".md", ".mdx"]
  ignore_dirs: [".git", "node_modules", "dist", "build"]

api:
  askai:
    timeout: 100
    retries: 3
