name: Unified Deploy Pipeline

on:
  workflow_dispatch:

jobs:
  deploy-homepage:
    uses: ./.github/workflows/deploy-homepage.yml
    secrets: inherit

  deploy-xcontrol-panel:
    uses: ./.github/workflows/deploy-xcontrol-panel.yml
    secrets: inherit

  deploy-xcontrol-server:
    uses: ./.github/workflows/deploy-xcontrol-server.yml
    secrets: inherit

  deploy-proxy-nginx:
    needs:
      - deploy-homepage
      - deploy-xcontrol-panel
      - deploy-xcontrol-server
    uses: ./.github/workflows/deploy-proxy-nginx.yml
    secrets: inherit

  setup-proxy-cn-homepage:
    needs:
      - deploy-homepage
      - deploy-xcontrol-panel
      - deploy-xcontrol-server
    uses: ./.github/workflows/setup-proxy-cn-homepage.yml
    secrets: inherit

  setup-proxy-global-homepage:
    needs:
      - deploy-homepage
      - deploy-xcontrol-panel
      - deploy-xcontrol-server
    uses: ./.github/workflows/setup-proxy-global-homepage.yml
    secrets: inherit
